//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Main {
    
    public partial class changepwd {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Telerik.Web.UI.RadStyleSheetManager RadStyleSheetManager1;
        protected Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected Telerik.Web.UI.RadFormDecorator RadFormDecorator1;
        protected System.Web.UI.WebControls.Label lblusername;
        protected System.Web.UI.WebControls.TextBox txtopwd;
        protected System.Web.UI.WebControls.TextBox txtnpwd;
        protected System.Web.UI.WebControls.TextBox txtcpwd;
        protected System.Web.UI.WebControls.Button btnsubmit;
        protected System.Web.UI.WebControls.Label lblerror;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfv1;
    }
}
