//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Management {
    
    public partial class AdditionType { 
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected Telerik.Web.UI.RadCodeBlock RadCodeBlock1;
        protected System.Web.UI.WebControls.DropDownList drplumsumswitch;
        protected Telerik.Web.UI.RadGrid RadGrid1;
        protected System.Web.UI.HtmlControls.HtmlInputHidden txtRadId;
        protected System.Web.UI.HtmlControls.HtmlInputHidden txtLumSum;
        protected System.Web.UI.WebControls.XmlDataSource XmldtTaxPayableTypeLumSumSwtich;
    }
}
