//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Management {
    
    public partial class AssignUserRights {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm employeeform;
        protected Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected System.Web.UI.WebControls.Label lblerror;
        protected System.Web.UI.WebControls.Button Button1;
        protected Telerik.Web.UI.RadFormDecorator RadFormDecorator1;
        protected System.Web.UI.WebControls.PlaceHolder placeHolder1;
        protected System.Web.UI.HtmlControls.HtmlInputHidden oHidden;
        protected System.Web.UI.WebControls.Label lblUserGroup;
        protected Telerik.Web.UI.RadTabStrip RadTabStrip1;
        protected Telerik.Web.UI.RadMultiPage RadMultiPage1;
    }
}
