//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Management {
    
    public partial class AssignAccomadation {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected Telerik.Web.UI.RadFormDecorator RadFormDecorator1;
        protected System.Web.UI.WebControls.DropDownList drpname;
        protected System.Web.UI.WebControls.DropDownList drpDormetry;
        protected System.Web.UI.WebControls.DropDownList drpCheckIN;
        protected Telerik.WebControls.RadDatePicker RadDatePicker2;
        protected System.Web.UI.WebControls.Button imgbtnsave;
        protected Telerik.Web.UI.RadGrid RadGrid1;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource2;
        protected Telerik.WebControls.RadAjaxManager RadAjaxManager1;
        protected System.Web.UI.WebControls.Label lblmsg;
    }
}
