//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Management {
    
    public partial class Bankedit {
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.TextBox txtbankcode;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfv1;
        protected System.Web.UI.WebControls.TextBox txtbankname;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfv2;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.ValidationSummary vsm1;
    }
}
