//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Management {
    
    public partial class GroupRights {
        protected System.Web.UI.HtmlControls.HtmlGenericControl rightsHeader;
        protected Telerik.Web.UI.RadGrid RadGrid1;
    }
}
