//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Reports {
    
    public partial class CustomConMainPage {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm employeeform;
        protected Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected System.Web.UI.WebControls.Label lblerror;
        protected Telerik.Web.UI.RadTabStrip tbsComp;
        protected Telerik.Web.UI.RadMultiPage tbsCompany;
        protected Telerik.Web.UI.RadPageView tbsEmp;
        protected Telerik.Web.UI.RadGrid RadGrid1;
        protected Telerik.Web.UI.RadGrid RadGrid2;
        protected System.Web.UI.WebControls.Button generateRpt;
        protected Telerik.Web.UI.RadPageView tbsPay;
        protected Telerik.Web.UI.RadGrid RadGrid3;
        protected Telerik.Web.UI.RadGrid RadGrid4;
        protected Telerik.WebControls.RadDatePicker dtp1;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvdtp1;
        protected Telerik.WebControls.RadDatePicker dtp2;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvdtp2;
        protected System.Web.UI.WebControls.RadioButtonList RadioButtonList1;
        protected System.Web.UI.WebControls.Button Button1;
        protected Telerik.Web.UI.RadPageView tbsAdditions;
        protected Telerik.Web.UI.RadGrid RadGrid5;
        protected Telerik.Web.UI.RadGrid RadGrid6;
        protected Telerik.WebControls.RadDatePicker RadDatePicker1;
        protected Telerik.WebControls.RadDatePicker RadDatePicker2;
        protected System.Web.UI.WebControls.RadioButtonList RadioButtonList2;
        protected System.Web.UI.WebControls.Button generateAddRpt;
        protected Telerik.Web.UI.RadPageView tbsDeductions;
        protected Telerik.Web.UI.RadGrid RadGrid9;
        protected Telerik.Web.UI.RadGrid RadGrid10;
        protected Telerik.WebControls.RadDatePicker RadDatePicker5;
        protected Telerik.WebControls.RadDatePicker RadDatePicker6;
        protected System.Web.UI.WebControls.RadioButtonList RadioButtonList3;
        protected System.Web.UI.WebControls.Button Button4;
        protected Telerik.Web.UI.RadPageView tbsClaims;
        protected Telerik.Web.UI.RadGrid RadGrid11;
        protected Telerik.Web.UI.RadGrid RadGrid12;
        protected Telerik.WebControls.RadDatePicker RadDatePicker7;
        protected Telerik.WebControls.RadDatePicker RadDatePicker8;
        protected System.Web.UI.WebControls.RadioButtonList RadioButtonList4;
        protected System.Web.UI.WebControls.Button Button5;
        protected Telerik.Web.UI.RadPageView tbsGroups;
        protected System.Web.UI.WebControls.DropDownList ddlCategory;
        protected Telerik.Web.UI.RadGrid RadGrid16;
        protected Telerik.Web.UI.RadGrid RadGrid8;
        protected System.Web.UI.WebControls.Button Button3;
        protected Telerik.Web.UI.RadPageView tbsLeaves;
        protected Telerik.Web.UI.RadGrid RadGrid7;
        protected Telerik.Web.UI.RadGrid RadGrid13;
        protected System.Web.UI.WebControls.RadioButtonList rdRepOption;
        protected System.Web.UI.WebControls.DropDownList drpYear;
        protected System.Web.UI.WebControls.Label lblStart;
        protected System.Web.UI.WebControls.DropDownList drpMonthStart;
        protected System.Web.UI.WebControls.Label lblEnd;
        protected System.Web.UI.WebControls.DropDownList drpMonthEnd;
        protected System.Web.UI.WebControls.Button btnGenLeaveRep;
        protected Telerik.Web.UI.RadPageView tbsTimesheet;
        protected Telerik.Web.UI.RadGrid RadGrid17;
        protected System.Web.UI.WebControls.RadioButtonList rdRepOptionTime;
        protected Telerik.Web.UI.RadDatePicker rdFrom;
        protected Telerik.Web.UI.RadDatePicker rdTo;
        protected System.Web.UI.WebControls.Button btnGo;
        protected Telerik.Web.UI.RadPageView tbsEmail;
        protected Telerik.Web.UI.RadGrid RadGrid14;
        protected Telerik.Web.UI.RadGrid RadGrid15;
        protected System.Web.UI.WebControls.RadioButtonList rdOptionEmail;
        protected System.Web.UI.WebControls.TextBox txtDocNo;
        protected System.Web.UI.WebControls.Button btnRptEmail;
        protected Telerik.Web.UI.RadAjaxLoadingPanel RadAjaxLoadingPanel1;
        protected System.Web.UI.WebControls.Image Image1;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource333;
        protected System.Web.UI.WebControls.XmlDataSource xmldtMonth;
        protected System.Web.UI.WebControls.XmlDataSource xmldtYear;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource3;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource4;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource2;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
        protected System.Web.UI.WebControls.XmlDataSource xmldtCompType;
    }
}
