//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Users {
    
    public partial class GroupTemplate {
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.TextBox txtgroupname;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
