//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Users {
    
    public partial class usertemplate {
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.TextBox txtUserName;
        protected System.Web.UI.WebControls.TextBox txtPwd;
        protected System.Web.UI.WebControls.TextBox txtConPwd;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.DropDownList drpUserGrp;
        protected System.Web.UI.WebControls.DropDownList drpUserStatus;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
