//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Company {
    
    public partial class giro {
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.DropDownList drpbankname;
        protected System.Web.UI.WebControls.TextBox txtvaluedate;
        protected System.Web.UI.WebControls.TextBox txtbranch;
        protected System.Web.UI.WebControls.TextBox txtbankaccno;
        protected System.Web.UI.WebControls.TextBox txtgiroaccountname;
        protected System.Web.UI.WebControls.Label lblDBS;
        protected System.Web.UI.WebControls.TextBox compbankcode;
        protected System.Web.UI.WebControls.Label lblDBS1;
        protected System.Web.UI.WebControls.Label lblMZ1;
        protected System.Web.UI.WebControls.TextBox txtApprover;
        protected System.Web.UI.WebControls.Label lblMZ11;
        protected System.Web.UI.WebControls.Label lblMZ2;
        protected System.Web.UI.WebControls.TextBox txtOperator;
        protected System.Web.UI.WebControls.Label lblMZ22;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnCancel;
    }
}
