//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Company {
    
    public partial class ShowCompanies {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected System.Web.UI.WebControls.Label lbltotalemp;
        protected System.Web.UI.WebControls.Label lbldbemp;
        protected System.Web.UI.WebControls.Label lbldiff;
        protected System.Web.UI.WebControls.Button bnrefresh;
        protected Telerik.Web.UI.RadCodeBlock RadCodeBlock1;
        protected System.Web.UI.HtmlControls.HtmlInputHidden flag;
        protected Telerik.Web.UI.RadGrid RadGrid1;
    }
}
