//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.Leaves {
    
    public partial class LeaveTransferYOS {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Telerik.Web.UI.RadScriptManager RadScriptManager1;
        protected Telerik.Web.UI.RadCodeBlock RadCodeBlock1;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected System.Web.UI.WebControls.Label lblTrdate;
        protected Telerik.WebControls.RadDatePicker rdTrdate;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.WebControls.TextBox txtfwd;
        protected System.Web.UI.WebControls.ImageButton imgbtnfetch;
        protected System.Web.UI.WebControls.Label lblerror;
        protected Telerik.Web.UI.RadGrid RadGrid1;
        protected System.Web.UI.WebControls.Button Button2;
        protected System.Web.UI.WebControls.Label lblmsg;
        protected System.Web.UI.WebControls.SqlDataSource SqlDataSource2;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
    }
}
