//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMEPayroll.TimeSheet {
    
    public partial class PayrollAdditionsAuto {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Telerik.Web.UI.RadScriptManager ScriptManager;
        protected SMEPayroll.Frames.TopRightMenu TopRightControl1;
        protected Telerik.Web.UI.RadCodeBlock RadCodeBlock4;
        protected System.Web.UI.WebControls.DropDownList drplumsum;
        protected System.Web.UI.WebControls.XmlDataSource XmldtTaxPayableTypeLumSumSwtich;
        protected System.Web.UI.WebControls.DropDownList drplumsumswitch;
        protected System.Web.UI.WebControls.DropDownList cmbYear;
        protected Telerik.Web.UI.RadDatePicker RadDatePicker1;
        protected Telerik.Web.UI.RadDatePicker RadDatePicker2;
        protected System.Web.UI.WebControls.Label lblcpf;
        protected System.Web.UI.WebControls.DropDownList drpaddtype;
        protected System.Web.UI.HtmlControls.HtmlTableRow tr1;
        protected System.Web.UI.WebControls.TextBox txtbasis_arriving_payment;
        protected System.Web.UI.HtmlControls.HtmlTableRow tr2;
        protected System.Web.UI.WebControls.TextBox txtservice_length;
        protected System.Web.UI.HtmlControls.HtmlTableRow tr3;
        protected System.Web.UI.WebControls.DropDownList drpiras_approval;
        protected System.Web.UI.HtmlControls.HtmlTableRow tr4;
        protected System.Web.UI.WebControls.TextBox txtiras_approval_date;
        protected System.Web.UI.HtmlControls.HtmlInputFile FileUpload;
        protected System.Web.UI.WebControls.RequiredFieldValidator rfvFileUpload;
        protected System.Web.UI.WebControls.RegularExpressionValidator revFileUpload;
        protected System.Web.UI.WebControls.Button CmdUpload;
        protected System.Web.UI.WebControls.ValidationSummary vldSum;
        protected System.Web.UI.HtmlControls.HtmlInputHidden txtLumSum;
    }
}
